name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
    - name: make clean
      run: make
    - name: make all
      run: make all
    - name: make fclean
      run: make fclean
    - name: make bonus
      run: make bonus
    - name: make re
      run: make re
